export const ADD_PLAYER = 'ADD_PLAYER';
export const CREATE_PLAYER = 'CREATE_PLAYER';
export const DELETE_PLAYER = 'DELETE_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const FETCH_READ_PLAYER_SUCCESS = 'FETCH_READ_PLAYER_SUCCESS'